title: Zhijin Guo
description: "Personal site refresh coming soon."
url: "https://ZhijinGuo.github.io"
baseurl: ""
remote_theme: pages-themes/cayman@v0.2.0
lang: en
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
social_links:
  - { platform: github,  user_url: "https://github.com/ZhijinGuo" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/zhijin-guo" }
